
name: Build Guardia Security

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
  pull_request:
    branches: [ main ]
  # Manual trigger from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # Skip this job if the commit message contains [skip ci]
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      # Uncomment when tests are implemented
      # - name: Run tests
      #   run: npm test
